name: AStrangeCore
main: org.example.Main
version: 1.0
description: Essentials moderation
api-version: 1.21.4
author: Quattra

commands:
  adminChat:
    usage: /adminChat
    description: sends message to all admins.
    permission: AStrangeCorePlugin.admin
  updateAdminList:
    usage: /updateAdminList
    description: updatesAdminList
    permission: AStrangeCorePlugin.engineer
  showAdd:
    usage: /showAdd
    description: shows add to every single player online that is not in the red or green teams excluding the admin teams.
    permission: AStrangeCorePlugin.engineer

    permissions:
      AStrangeCorePlugin.admin:
        description: allows access to AdminChat and simple moderator tools. Allows for vision of AntiCheat (in the future).
        default: op
      AStrangeCorePlugin.engineer:
        description: Allows for administrator privileges plus backend commands that update data in the Server.
        default: false
        children:
          AStrangeCorePlugin.admin: true
